// The reference volumes behind the Stack Atlas.
//
// These are the things you meet on a client's existing estate — the half of an
// evaluation that is not about what we would build, but about what is already
// there. Every entry answers the same three questions: what is it, where do you
// meet it, and what should you watch for.
//
// The "watch for" line is the load-bearing one. It is the difference between a
// lookup table and something that changes a quote.

/** How much caution an entry warrants when found on a client system. */
export type Posture = "Safe" | "Use with care" | "Avoid";
/** Rough integration effort, not difficulty of understanding. */
export type Effort = "Low" | "Medium" | "High";
/** Whether something is a live choice or an inherited liability. */
export type Standing = "Current" | "Legacy";

interface ReferenceBase {
  name: string;
  /** Sub-group within the volume. */
  group: string;
  whatItIs: string;
  whereYouMeetIt: string;
  watchFor: string;
}

export interface ProtocolEntry extends ReferenceBase {
  /** Default port(s), as you would find them in a firewall rule. */
  port: string;
  posture: Posture;
}

export interface FormatEntry extends ReferenceBase {
  effort: Effort;
}

export interface AuthEntry extends ReferenceBase {
  posture: Posture;
}

export interface InfraEntry extends ReferenceBase {
  standing: Standing;
}

export interface StackEntry {
  name: string;
  group: string;
  standing: Standing;
  frontEnd: string;
  backEnd: string;
  data: string;
  hosting: string;
  bestFor: string;
  watchOutFor: string;
}

export const PROTOCOL_GROUPS: string[] = ["File transfer", "Web & API", "Mail", "Directory & access", "Remote access", "File sharing", "Messaging", "Network services", "Data access"];

export const PROTOCOLS: ProtocolEntry[] = [
  { name: "FTP", group: "File transfer", port: "21 / 20", posture: "Avoid",
    whatItIs: "The original file transfer protocol. Credentials and file contents cross the wire in clear text.",
    whereYouMeetIt: "Any system built before about 2010 that exchanges files with a vendor, bank or distributor.",
    watchFor: "Plain-text passwords. If a client is on FTP, that is a finding, not a detail — move them to SFTP and say so in writing." },
  { name: "FTPS", group: "File transfer", port: "990 / 21", posture: "Use with care",
    whatItIs: "FTP wrapped in TLS. Keeps FTP's two-connection design, which firewalls hate.",
    whereYouMeetIt: "Banks and older EDI trading partners who added TLS rather than move to SSH.",
    watchFor: "Passive-mode port ranges have to be opened explicitly. Expect a firewall conversation, not a config change." },
  { name: "SFTP", group: "File transfer", port: "22", posture: "Safe",
    whatItIs: "File transfer over SSH. Unrelated to FTP despite the name.",
    whereYouMeetIt: "The default for scheduled file exchange with anyone competent.",
    watchFor: "Key management is the real work. Decide early whether you hold the private key or they do." },
  { name: "SCP", group: "File transfer", port: "22", posture: "Use with care",
    whatItIs: "Copy files over SSH. Simple, one-shot, no directory listing.",
    whereYouMeetIt: "Deploy scripts and ad-hoc server-to-server copies.",
    watchFor: "The protocol is deprecated in OpenSSH in favour of SFTP. Fine for scripts, wrong for an integration." },
  { name: "rsync", group: "File transfer", port: "873 / 22", posture: "Safe",
    whatItIs: "Delta-transfer sync — only the changed blocks move.",
    whereYouMeetIt: "Backups, large media libraries, mirroring between servers.",
    watchFor: "Run it over SSH, never the standalone rsync daemon on 873, which is unauthenticated by default." },
  { name: "TFTP", group: "File transfer", port: "69 (UDP)", posture: "Avoid",
    whatItIs: "Trivial FTP. No authentication whatsoever, by design.",
    whereYouMeetIt: "Network device firmware, PXE boot, VoIP phone provisioning.",
    watchFor: "If it is reachable from anything but an isolated provisioning VLAN, that is an open door." },
  { name: "WebDAV", group: "File transfer", port: "80 / 443", posture: "Use with care",
    whatItIs: "HTTP extended with file operations — the protocol behind mapped network drives over the web.",
    whereYouMeetIt: "SharePoint, Nextcloud, older document management systems.",
    watchFor: "Windows' WebDAV client is notoriously fussy over HTTPS. Test on the client's actual machines, not yours." },
  { name: "AS2", group: "File transfer", port: "80 / 443", posture: "Safe",
    whatItIs: "Signed, encrypted EDI document exchange over HTTP with a signed receipt (MDN) proving delivery.",
    whereYouMeetIt: "Retail and pharma supply chains. Walmart, Target and their suppliers run on it.",
    watchFor: "Certificate exchange with the trading partner takes weeks, not hours. Put it on the critical path." },
  { name: "OFTP2", group: "File transfer", port: "6619", posture: "Safe",
    whatItIs: "Odette FTP — the European automotive equivalent of AS2.",
    whereYouMeetIt: "Automotive tier-one and tier-two suppliers, mostly in Europe.",
    watchFor: "Narrow vendor ecosystem. Buy a gateway; do not implement the protocol." },
  { name: "HTTP/1.1", group: "Web & API", port: "80", posture: "Avoid",
    whatItIs: "The web's workhorse request/response protocol, unencrypted.",
    whereYouMeetIt: "Internal tools, old admin panels, IoT devices, anything behind \"it's on the LAN\".",
    watchFor: "Unencrypted anywhere is now a finding. Browsers increasingly refuse features on it entirely." },
  { name: "HTTPS (TLS 1.2 / 1.3)", group: "Web & API", port: "443", posture: "Safe",
    whatItIs: "HTTP over TLS. 1.3 is the current standard; 1.2 is acceptable, anything below is not.",
    whereYouMeetIt: "Everywhere. The question is only which version and how the certificate is managed.",
    watchFor: "Check for expiring certs and TLS 1.0/1.1 still enabled — both are common audit findings." },
  { name: "HTTP/2", group: "Web & API", port: "443", posture: "Safe",
    whatItIs: "Multiplexed HTTP over one connection. Removes head-of-line blocking at the HTTP layer.",
    whereYouMeetIt: "Any modern CDN or load balancer, usually already on without anyone deciding.",
    watchFor: "Server push is deprecated and removed from browsers. Do not design around it." },
  { name: "HTTP/3 (QUIC)", group: "Web & API", port: "443 (UDP)", posture: "Safe",
    whatItIs: "HTTP over QUIC, on UDP. Much better on lossy mobile networks.",
    whereYouMeetIt: "Cloudflare, Fastly and modern CDNs, transparently.",
    watchFor: "Some corporate firewalls block UDP 443 outright and silently fall back to HTTP/2. Fine, but know it happens." },
  { name: "WebSocket", group: "Web & API", port: "443", posture: "Safe",
    whatItIs: "A persistent two-way connection upgraded from an HTTP request.",
    whereYouMeetIt: "Chat, collaborative editing, live dashboards, trading screens.",
    watchFor: "Reconnection and state resync are the actual work. Load balancers need sticky sessions or a shared backplane." },
  { name: "Server-Sent Events", group: "Web & API", port: "443", posture: "Safe",
    whatItIs: "A one-way stream from server to browser over plain HTTP.",
    whereYouMeetIt: "Progress bars, live status feeds, LLM token streaming.",
    watchFor: "Reach for this before WebSocket. Simpler, survives proxies better, and covers most \"make it live\" requests." },
  { name: "gRPC", group: "Web & API", port: "443 / 50051", posture: "Safe",
    whatItIs: "Binary RPC over HTTP/2 with Protobuf contracts and generated clients.",
    whereYouMeetIt: "Service-to-service traffic inside a system's own walls.",
    watchFor: "Browsers cannot speak it natively — you need grpc-web and a proxy. Rarely the right choice for a public API." },
  { name: "SOAP", group: "Web & API", port: "80 / 443", posture: "Use with care",
    whatItIs: "XML-envelope RPC with a WSDL contract, and often WS-Security on top.",
    whereYouMeetIt: "Government portals, insurance carriers, shipping carriers, older ERPs.",
    watchFor: "The WSDL is usually correct and the vendor's example is usually wrong. Budget time for namespace archaeology." },
  { name: "REST", group: "Web & API", port: "443", posture: "Safe",
    whatItIs: "Resource-oriented HTTP. Not a standard so much as a widely shared convention.",
    whereYouMeetIt: "The default for almost every integration written this century.",
    watchFor: "\"REST\" in a vendor's docs can mean anything. Ask for an OpenAPI spec before quoting." },
  { name: "GraphQL", group: "Web & API", port: "443", posture: "Use with care",
    whatItIs: "A single endpoint where the caller specifies the shape of the response.",
    whereYouMeetIt: "Mobile apps and front-ends aggregating several back-end services.",
    watchFor: "Query depth and cost limiting are not optional on a public endpoint — without them it is a denial-of-service surface." },
  { name: "JSON-RPC", group: "Web & API", port: "varies", posture: "Safe",
    whatItIs: "Minimal remote procedure call over JSON. No resource semantics.",
    whereYouMeetIt: "Blockchain nodes, Bitcoin/Ethereum RPC, some internal tooling.",
    watchFor: "No standard error taxonomy. Every implementation invents its own; read theirs." },
  { name: "XML-RPC", group: "Web & API", port: "80 / 443", posture: "Avoid",
    whatItIs: "The 1998 ancestor of SOAP.",
    whereYouMeetIt: "WordPress (xmlrpc.php), older CMS and blog integrations.",
    watchFor: "On WordPress it is a standing brute-force and amplification target. Disable it unless something specific needs it." },
  { name: "OData", group: "Web & API", port: "443", posture: "Use with care",
    whatItIs: "A REST convention with a query language in the URL — filtering, sorting and expansion built in.",
    whereYouMeetIt: "SAP, Microsoft Dynamics, SharePoint, Business Central.",
    watchFor: "Expressive enough that clients can write accidental table scans against production." },
  { name: "Webhooks", group: "Web & API", port: "443", posture: "Safe",
    whatItIs: "The far system calls you when something happens. A doorbell, not a stakeout.",
    whereYouMeetIt: "Stripe, GitHub, form providers, anything event-driven.",
    watchFor: "Verify the signature, always, and make the handler idempotent — you will get duplicates." },
  { name: "SMTP", group: "Mail", port: "25 / 587 / 465", posture: "Use with care",
    whatItIs: "The protocol that sends mail. 587 with STARTTLS is the modern submission port.",
    whereYouMeetIt: "Every application that sends a notification, invoice or password reset.",
    watchFor: "Deliverability is the real project: SPF, DKIM and DMARC must all be right or the mail silently goes to spam." },
  { name: "IMAP", group: "Mail", port: "993", posture: "Safe",
    whatItIs: "Reads mail while leaving it on the server, with folder state synced.",
    whereYouMeetIt: "Mailbox integrations, shared inboxes, ticket systems that ingest email.",
    watchFor: "Google and Microsoft have both killed basic auth — OAuth is now mandatory for both." },
  { name: "POP3", group: "Mail", port: "995", posture: "Use with care",
    whatItIs: "Downloads mail and traditionally deletes it from the server.",
    whereYouMeetIt: "Old scanners, copiers, alarm panels and line-of-business apps.",
    watchFor: "Two systems polling the same POP3 box will fight over messages. Move to IMAP or a dedicated address." },
  { name: "Exchange Web Services", group: "Mail", port: "443", posture: "Use with care",
    whatItIs: "Microsoft's SOAP API for mailboxes, calendars and contacts.",
    whereYouMeetIt: "On-premise Exchange and older Office 365 integrations.",
    watchFor: "Retired for Exchange Online in October 2026 — anything using it against O365 needs to move to Graph." },
  { name: "Microsoft Graph", group: "Mail", port: "443", posture: "Safe",
    whatItIs: "Microsoft's unified REST API for mail, calendar, files, Teams and directory.",
    whereYouMeetIt: "The current answer for anything touching Microsoft 365.",
    watchFor: "Admin consent for application permissions is a governance conversation, not a code task. Start it early." },
  { name: "LDAP", group: "Directory & access", port: "389", posture: "Avoid",
    whatItIs: "Directory lookup — users, groups, org structure. Unencrypted on 389.",
    whereYouMeetIt: "Active Directory, OpenLDAP, older intranet authentication.",
    watchFor: "Bind credentials in clear text. Use LDAPS or StartTLS; Microsoft has been pushing signing enforcement for years." },
  { name: "LDAPS", group: "Directory & access", port: "636", posture: "Safe",
    whatItIs: "LDAP over TLS.",
    whereYouMeetIt: "Enterprise directory integration done properly.",
    watchFor: "Often uses an internal CA. Your app's trust store needs that root, which is a deployment step people forget." },
  { name: "Kerberos", group: "Directory & access", port: "88", posture: "Safe",
    whatItIs: "Ticket-based authentication. The thing that actually signs Windows users in.",
    whereYouMeetIt: "Windows domains, SQL Server integrated auth, intranet single sign-on.",
    watchFor: "Brutally sensitive to clock skew and DNS. Debugging it from outside the domain is painful — get a domain-joined test box." },
  { name: "RADIUS", group: "Directory & access", port: "1812 / 1813", posture: "Use with care",
    whatItIs: "Centralised authentication for network access.",
    whereYouMeetIt: "Wi-Fi, VPN concentrators, switches.",
    watchFor: "The shared secret is often the same across every device in the estate. Worth checking." },
  { name: "SAML 2.0", group: "Directory & access", port: "443", posture: "Safe",
    whatItIs: "XML assertions passed through the browser for single sign-on.",
    whereYouMeetIt: "Enterprise SSO — Okta, Entra ID, Ping, ADFS.",
    watchFor: "Signature validation and clock skew cause most failures. Certificates expire and nobody is watching." },
  { name: "SSH", group: "Remote access", port: "22", posture: "Safe",
    whatItIs: "Encrypted shell, tunnelling and file transfer.",
    whereYouMeetIt: "Every Linux server, most network gear, deployment pipelines.",
    watchFor: "Password auth should be off and keys should be rotated. Ask who still has a key from a previous vendor." },
  { name: "Telnet", group: "Remote access", port: "23", posture: "Avoid",
    whatItIs: "Unencrypted remote shell.",
    whereYouMeetIt: "Old switches, industrial controllers, AS/400 green-screen sessions.",
    watchFor: "Everything including the password is in clear text. If it is on, it needs a written justification or an off switch." },
  { name: "RDP", group: "Remote access", port: "3389", posture: "Use with care",
    whatItIs: "Microsoft's remote desktop protocol.",
    whereYouMeetIt: "Windows servers, client jump boxes, the machine that runs one critical application.",
    watchFor: "Exposed to the internet it is a primary ransomware entry point. Behind a VPN or a broker, never open." },
  { name: "VNC", group: "Remote access", port: "5900", posture: "Use with care",
    whatItIs: "Cross-platform screen sharing.",
    whereYouMeetIt: "Kiosks, Raspberry Pi, industrial HMIs.",
    watchFor: "Base protocol authentication is weak and often left at defaults. Tunnel it over SSH." },
  { name: "SMB / CIFS", group: "File sharing", port: "445", posture: "Use with care",
    whatItIs: "Windows file and printer sharing.",
    whereYouMeetIt: "Mapped drives, scan-to-folder, shared \"the data lives here\" folders.",
    watchFor: "SMBv1 must be off — it is the WannaCry vector. Never expose 445 beyond the LAN." },
  { name: "NFS", group: "File sharing", port: "2049", posture: "Use with care",
    whatItIs: "Unix network file system.",
    whereYouMeetIt: "Linux servers sharing storage, NAS appliances, container volumes.",
    watchFor: "NFSv3 trusts whatever user ID the client claims. Use v4 with Kerberos, or keep it on a private network." },
  { name: "MQTT", group: "Messaging", port: "1883 / 8883", posture: "Use with care",
    whatItIs: "Lightweight publish/subscribe for constrained devices.",
    whereYouMeetIt: "IoT sensors, telemetry, building automation, vehicle tracking.",
    watchFor: "1883 is unencrypted; use 8883. Anonymous brokers open to the internet are a recurring news story." },
  { name: "AMQP", group: "Messaging", port: "5672 / 5671", posture: "Safe",
    whatItIs: "Broker-based messaging with routing, acknowledgements and durability.",
    whereYouMeetIt: "RabbitMQ, Azure Service Bus, enterprise job queues.",
    watchFor: "Dead-letter handling is the part teams skip and then need at 2am." },
  { name: "Kafka protocol", group: "Messaging", port: "9092", posture: "Safe",
    whatItIs: "Partitioned, replayable log rather than a queue. Consumers track their own position.",
    whereYouMeetIt: "Event streaming, change-data-capture, analytics pipelines.",
    watchFor: "Operationally heavy. If the requirement is \"a queue\", this is probably too much machine." },
  { name: "STOMP", group: "Messaging", port: "61613", posture: "Use with care",
    whatItIs: "Simple text-based messaging, often bridged to WebSocket.",
    whereYouMeetIt: "ActiveMQ, browser-facing message feeds.",
    watchFor: "Thin on features. Usually a sign the real broker is something else underneath." },
  { name: "DNS", group: "Network services", port: "53", posture: "Safe",
    whatItIs: "Name resolution. Also, quietly, the cause of the outage.",
    whereYouMeetIt: "Every cutover, every domain move, every email deliverability problem.",
    watchFor: "Find out who actually controls the zone before promising a launch date. It is often nobody the client remembers." },
  { name: "NTP", group: "Network services", port: "123 (UDP)", posture: "Safe",
    whatItIs: "Clock synchronisation.",
    whereYouMeetIt: "Everywhere, invisibly, until it breaks.",
    watchFor: "Skewed clocks break Kerberos, TOTP, TLS and signed webhooks all at once. Check it first when auth fails weirdly." },
  { name: "SNMP", group: "Network services", port: "161", posture: "Use with care",
    whatItIs: "Device monitoring and management.",
    whereYouMeetIt: "Printers, switches, UPSs, environmental sensors.",
    watchFor: "v1 and v2c use a clear-text community string, usually still \"public\". Use v3 or restrict by source address." },
  { name: "SIP / RTP", group: "Network services", port: "5060 / dynamic", posture: "Use with care",
    whatItIs: "Call setup (SIP) and the media stream itself (RTP).",
    whereYouMeetIt: "VoIP phone systems, call-centre integrations, click-to-call features.",
    watchFor: "NAT traversal is the whole problem. An exposed, badly configured SIP trunk gets used for toll fraud within days." },
  { name: "WebRTC", group: "Network services", port: "dynamic (UDP)", posture: "Safe",
    whatItIs: "Peer-to-peer audio, video and data between browsers.",
    whereYouMeetIt: "In-app video calls, screen sharing, live support.",
    watchFor: "You still need STUN and usually TURN servers. TURN bandwidth is a real, ongoing cost line." },
  { name: "ODBC / JDBC", group: "Data access", port: "varies", posture: "Use with care",
    whatItIs: "Standard driver interfaces for talking to a database directly.",
    whereYouMeetIt: "Reporting tools, Access front-ends, ETL jobs, Excel connections.",
    watchFor: "Direct database access hands out far more than the caller needs. Prefer a view, a replica or an API." },
  { name: "TDS", group: "Data access", port: "1433", posture: "Use with care",
    whatItIs: "The wire protocol behind SQL Server and Sybase.",
    whereYouMeetIt: "Anything connecting to SQL Server.",
    watchFor: "Encryption is a connection-string setting that is very often left off. Turn it on." },
  { name: "IPsec / WireGuard", group: "Network services", port: "500 / 51820", posture: "Safe",
    whatItIs: "Site-to-site and client VPN tunnels.",
    whereYouMeetIt: "Connecting to a client's private network to reach an internal system.",
    watchFor: "Getting a tunnel approved by the client's IT can take longer than the integration itself. Ask on day one." },
];

export const FORMAT_GROUPS: string[] = ["Tabular & flat", "Structured text", "Binary & columnar", "Trade & supply chain", "Healthcare", "Financial", "Documents", "Web & interchange", "Geospatial", "Engineering"];

export const FORMATS: FormatEntry[] = [
  { name: "CSV", group: "Tabular & flat", effort: "Low",
    whatItIs: "Comma-separated text. The lowest common denominator of data exchange.",
    whereYouMeetIt: "Every export button ever built. Usually the first sample a client sends you.",
    watchFor: "There is no CSV standard. Ask for the delimiter, quoting rule, encoding and line ending before you write a parser." },
  { name: "TSV", group: "Tabular & flat", effort: "Low",
    whatItIs: "Tab-separated. Marginally safer than CSV because tabs appear less often in real data.",
    whereYouMeetIt: "Database dumps, bioinformatics, older Unix pipelines.",
    watchFor: "Still breaks on embedded newlines. Check for them in free-text fields." },
  { name: "Fixed-width flat file", group: "Tabular & flat", effort: "Medium",
    whatItIs: "Fields defined by character position, not delimiters. No header, no self-description.",
    whereYouMeetIt: "Mainframe extracts, payroll, bank files, insurance bordereaux.",
    watchFor: "Useless without the record layout document. Get it in writing before quoting — the file alone tells you nothing." },
  { name: "COBOL copybook", group: "Tabular & flat", effort: "High",
    whatItIs: "The record layout for mainframe data: PIC clauses, OCCURS, REDEFINES, packed decimals.",
    whereYouMeetIt: "Any COBOL or IBM i extract, usually alongside a fixed-width or EBCDIC file.",
    watchFor: "COMP-3 packed decimal and signed overpunch fields are where naive parsers silently corrupt money." },
  { name: "EBCDIC", group: "Tabular & flat", effort: "Medium",
    whatItIs: "IBM's mainframe character encoding. Not ASCII, and not a superset of it.",
    whereYouMeetIt: "z/OS and IBM i files delivered without conversion.",
    watchFor: "Code page matters — 037 and 1140 differ on currency symbols. Ask which one." },
  { name: "JSON", group: "Structured text", effort: "Low",
    whatItIs: "The default interchange format of the modern web.",
    whereYouMeetIt: "Every REST API, most config, document databases.",
    watchFor: "No native date or decimal type. Money as a float is a bug you will find in production." },
  { name: "JSON Lines", group: "Structured text", effort: "Low",
    whatItIs: "One JSON object per line. Streamable and appendable.",
    whereYouMeetIt: "Log shipping, bulk exports, LLM training and eval sets.",
    watchFor: "Genuinely underused — reach for it over a giant JSON array for anything you have to stream." },
  { name: "XML", group: "Structured text", effort: "Medium",
    whatItIs: "Verbose, namespaced, schema-validated markup.",
    whereYouMeetIt: "SOAP, enterprise systems, government filings, publishing, finance.",
    watchFor: "Disable external entity resolution in your parser. XXE is still one of the most common findings in older systems." },
  { name: "YAML", group: "Structured text", effort: "Low",
    whatItIs: "Indentation-sensitive configuration format.",
    whereYouMeetIt: "Kubernetes, CI pipelines, Ansible, application config.",
    watchFor: "Unquoted `no` parses as false and `1.0` as a number. Country code NO has ruined real deployments." },
  { name: "TOML", group: "Structured text", effort: "Low",
    whatItIs: "Explicit, unambiguous configuration format.",
    whereYouMeetIt: "Cargo, Poetry, Hugo, modern tooling config.",
    watchFor: "Fine for config, wrong for data interchange. Nested arrays of tables get unreadable fast." },
  { name: "INI", group: "Structured text", effort: "Low",
    whatItIs: "Sections and key-value pairs. Predates everything.",
    whereYouMeetIt: "Windows applications, PHP config, legacy desktop software.",
    watchFor: "No agreed nesting or type rules. Every parser differs on comments and duplicates." },
  { name: "Protocol Buffers", group: "Binary & columnar", effort: "Medium",
    whatItIs: "Schema-first binary encoding with generated code in every major language.",
    whereYouMeetIt: "gRPC services, high-volume internal messaging.",
    watchFor: "Field numbers are the contract, not the names. Reusing a retired number silently corrupts data." },
  { name: "Avro", group: "Binary & columnar", effort: "Medium",
    whatItIs: "Binary rows with the schema carried alongside, built for evolution.",
    whereYouMeetIt: "Kafka topics, Hadoop-era data lakes.",
    watchFor: "Needs a schema registry to be worth it. Without one you have binary blobs nobody can read." },
  { name: "Parquet", group: "Binary & columnar", effort: "Low",
    whatItIs: "Columnar storage with compression and predicate pushdown.",
    whereYouMeetIt: "Data lakes, Snowflake and BigQuery staging, analytics exports.",
    watchFor: "The right default for any analytical extract over a few hundred thousand rows. Ask for it instead of CSV." },
  { name: "ORC", group: "Binary & columnar", effort: "Medium",
    whatItIs: "Columnar format from the Hive ecosystem.",
    whereYouMeetIt: "Hadoop and Hive estates.",
    watchFor: "Parquet has broader tool support. If you get a choice, take Parquet." },
  { name: "Apache Arrow", group: "Binary & columnar", effort: "Low",
    whatItIs: "In-memory columnar layout for zero-copy transfer between tools.",
    whereYouMeetIt: "Under the hood of Polars, DuckDB, pandas 2, and increasingly the wire format too.",
    watchFor: "An implementation detail more often than a deliverable — but it is why some pipelines are ten times faster." },
  { name: "MessagePack", group: "Binary & columnar", effort: "Low",
    whatItIs: "Compact binary JSON.",
    whereYouMeetIt: "Game networking, IoT, Redis payloads.",
    watchFor: "Saves bytes, costs debuggability. Only worth it when the wire is genuinely the bottleneck." },
  { name: "HDF5", group: "Binary & columnar", effort: "Medium",
    whatItIs: "Hierarchical scientific data with array slicing.",
    whereYouMeetIt: "Research, engineering simulation, sensor archives.",
    watchFor: "Concurrent write support is poor. Treat files as single-writer." },
  { name: "EDI X12", group: "Trade & supply chain", effort: "High",
    whatItIs: "The North American EDI standard. Numbered transaction sets: 850 purchase order, 810 invoice, 856 ASN.",
    whereYouMeetIt: "Retail, distribution, logistics, healthcare claims. Anyone selling into a big-box retailer.",
    watchFor: "Every trading partner has its own implementation guide. \"We support X12\" means almost nothing on its own." },
  { name: "EDIFACT", group: "Trade & supply chain", effort: "High",
    whatItIs: "The UN/international EDI standard. ORDERS, INVOIC, DESADV.",
    whereYouMeetIt: "European and Asian supply chains, automotive, shipping.",
    watchFor: "Same trap as X12, plus regional subsets. Buy a translator; do not parse it by hand." },
  { name: "UBL / PEPPOL", group: "Trade & supply chain", effort: "Medium",
    whatItIs: "XML business documents and the European e-invoicing network that carries them.",
    whereYouMeetIt: "EU public-sector invoicing, increasingly mandatory e-invoicing regimes.",
    watchFor: "Access-point providers do the heavy lifting. Integrate to one rather than joining the network yourself." },
  { name: "cXML", group: "Trade & supply chain", effort: "Medium",
    whatItIs: "Ariba's XML for punchout catalogues and procurement.",
    whereYouMeetIt: "SAP Ariba, Coupa and corporate purchasing portals.",
    watchFor: "Punchout session handoff is fiddly and hard to test without the buyer's sandbox." },
  { name: "GS1 / GTIN barcodes", group: "Trade & supply chain", effort: "Low",
    whatItIs: "Global product identifiers and the barcode symbologies that carry them.",
    whereYouMeetIt: "Retail, warehouse, any inventory system.",
    watchFor: "GTIN-12, 13 and 14 are the same number padded differently. Store the check digit and normalise on write." },
  { name: "HL7 v2.x", group: "Healthcare", effort: "High",
    whatItIs: "Pipe-delimited clinical messages. Segments like MSH, PID, OBR, OBX.",
    whereYouMeetIt: "Hospital systems, labs, radiology, admissions. Still the dominant format in production.",
    watchFor: "Endlessly site-customised through Z-segments. Every interface is bespoke — never quote one as generic work." },
  { name: "HL7 FHIR", group: "Healthcare", effort: "Medium",
    whatItIs: "Modern REST and JSON healthcare API with defined resources.",
    whereYouMeetIt: "Patient apps, US interoperability mandates, new clinical integrations.",
    watchFor: "Far more pleasant than v2, but the profile — US Core, UK Core — determines what is actually required." },
  { name: "CDA / CCD", group: "Healthcare", effort: "High",
    whatItIs: "XML clinical documents — the continuity-of-care summary.",
    whereYouMeetIt: "Record transfer between providers, Meaningful Use era systems.",
    watchFor: "Human-readable and machine-readable halves can disagree. The narrative block is what clinicians actually read." },
  { name: "DICOM", group: "Healthcare", effort: "High",
    whatItIs: "Medical imaging format and network protocol in one.",
    whereYouMeetIt: "Radiology, cardiology, PACS systems, imaging devices.",
    watchFor: "Files carry patient identifiers in the header. De-identification is a compliance task, not a checkbox." },
  { name: "NCPDP SCRIPT", group: "Healthcare", effort: "High",
    whatItIs: "Electronic prescribing messages.",
    whereYouMeetIt: "Pharmacy systems, e-prescribing, prescription benefit checks.",
    watchFor: "Certification is required to transact. This is a licensing project as much as a technical one." },
  { name: "ISO 8583", group: "Financial", effort: "High",
    whatItIs: "The card transaction message format. Bitmap-driven binary fields.",
    whereYouMeetIt: "Card acquirers, ATMs, POS terminals, switch platforms.",
    watchFor: "If you are touching this you are in PCI scope. Confirm that before writing a line of code." },
  { name: "ISO 20022", group: "Financial", effort: "High",
    whatItIs: "XML financial messaging replacing SWIFT MT for payments and reporting.",
    whereYouMeetIt: "Bank payments, SEPA, and the ongoing global migration off MT.",
    watchFor: "Migration deadlines are live. A bank integration written to MT today has a known expiry date." },
  { name: "SWIFT MT", group: "Financial", effort: "High",
    whatItIs: "The legacy bank message format — MT103 payments, MT940 statements.",
    whereYouMeetIt: "Corporate treasury, correspondent banking, older cash management.",
    watchFor: "Being replaced by ISO 20022. Ask the bank for their cutover date before building to it." },
  { name: "NACHA ACH", group: "Financial", effort: "High",
    whatItIs: "US bank transfer batch file format, fixed-width and 94 characters per record.",
    whereYouMeetIt: "Payroll, direct debit, vendor payments.",
    watchFor: "Return codes arrive days later. The unhappy path is most of the work; use a processor unless you must not." },
  { name: "BAI2", group: "Financial", effort: "Medium",
    whatItIs: "Bank statement and balance reporting file.",
    whereYouMeetIt: "Treasury systems and automated cash reconciliation.",
    watchFor: "Bank-specific type codes. Get a sample file from the actual bank, not the spec." },
  { name: "OFX / QFX", group: "Financial", effort: "Medium",
    whatItIs: "Open Financial Exchange — bank and card transaction download.",
    whereYouMeetIt: "Quicken, personal finance tools, older accounting imports.",
    watchFor: "Most US banks have moved to aggregator APIs. Treat this as a fallback path." },
  { name: "IIF / QBO", group: "Financial", effort: "Low",
    whatItIs: "QuickBooks import formats.",
    whereYouMeetIt: "Bookkeeping imports, migration from another accounting package.",
    watchFor: "IIF is deprecated and silently drops fields. Use the QuickBooks API where you can." },
  { name: "PDF", group: "Documents", effort: "Low",
    whatItIs: "Fixed-layout document format.",
    whereYouMeetIt: "Invoices, contracts, reports, statements — the default deliverable.",
    watchFor: "Extracting reliable data out of a PDF is a different, much harder project than producing one. Price them separately." },
  { name: "PDF/A", group: "Documents", effort: "Medium",
    whatItIs: "Archival PDF with embedded fonts and no external dependencies.",
    whereYouMeetIt: "Legal filing, records retention, government submission.",
    watchFor: "Validation is strict. A PDF that opens fine can still fail PDF/A conformance." },
  { name: "OOXML (DOCX / XLSX)", group: "Documents", effort: "Low",
    whatItIs: "Microsoft Office's zipped XML formats.",
    whereYouMeetIt: "Every client document, every spreadsheet you are asked to \"just import\".",
    watchFor: "Spreadsheets carry formulas, merged cells and typed dates. Treat one as a small database, not a table." },
  { name: "Legacy XLS / DOC", group: "Documents", effort: "Medium",
    whatItIs: "The pre-2007 binary Office formats.",
    whereYouMeetIt: "Long-lived templates and macro workbooks nobody dares touch.",
    watchFor: "Often carry VBA that is load-bearing business logic. Read it before proposing a replacement." },
  { name: "MDB / ACCDB", group: "Documents", effort: "Medium",
    whatItIs: "Microsoft Access database files.",
    whereYouMeetIt: "Departmental applications that outgrew a spreadsheet and became the system of record.",
    watchFor: "Usually one file on a share drive with no backup. Migration is a rescue, and should be scoped as one." },
  { name: "DBF", group: "Documents", effort: "Medium",
    whatItIs: "dBase / FoxPro table files.",
    whereYouMeetIt: "Older retail, dental, legal and GIS software.",
    watchFor: "Memo fields live in a separate .fpt or .dbt file. Copy the whole directory, not just the .dbf." },
  { name: "iCalendar", group: "Web & interchange", effort: "Low",
    whatItIs: "Calendar events and recurrence rules.",
    whereYouMeetIt: "Booking systems, calendar feeds, appointment reminders.",
    watchFor: "Recurrence with exceptions and time zones is genuinely hard. Use a library, never hand-roll RRULE." },
  { name: "vCard", group: "Web & interchange", effort: "Low",
    whatItIs: "Contact card format.",
    whereYouMeetIt: "Contact export and import, QR business cards.",
    watchFor: "Versions 2.1, 3.0 and 4.0 differ enough to break naive parsers. Detect the version." },
  { name: "GeoJSON", group: "Geospatial", effort: "Low",
    whatItIs: "JSON for points, lines and polygons.",
    whereYouMeetIt: "Web maps, service areas, delivery zones, store locators.",
    watchFor: "Coordinates are longitude first. Half of all map bugs are that pair the wrong way round." },
  { name: "Shapefile", group: "Geospatial", effort: "Medium",
    whatItIs: "The Esri GIS format — actually three-plus files that must travel together.",
    whereYouMeetIt: "Municipal data, parcels, utilities, surveying.",
    watchFor: "Field names are capped at ten characters and the projection lives in the .prj. Missing it means the data lands in the ocean." },
  { name: "KML / GPX", group: "Geospatial", effort: "Low",
    whatItIs: "Google Earth overlays and GPS track logs.",
    whereYouMeetIt: "Field routes, asset tracking, fleet history.",
    watchFor: "Fine for display, weak for analysis. Convert to GeoJSON or PostGIS for anything computational." },
  { name: "RSS / Atom", group: "Web & interchange", effort: "Low",
    whatItIs: "Syndication feeds.",
    whereYouMeetIt: "Blogs, podcasts, press releases, job boards.",
    watchFor: "Still the most reliable way to ingest a site that has no API." },
  { name: "SCORM / xAPI", group: "Web & interchange", effort: "Medium",
    whatItIs: "E-learning packaging and activity tracking standards.",
    whereYouMeetIt: "Corporate LMS, compliance training, course platforms.",
    watchFor: "SCORM 1.2 is ancient and still the most widely required. xAPI is better and less often accepted." },
  { name: "MARC 21", group: "Web & interchange", effort: "High",
    whatItIs: "Library bibliographic records.",
    whereYouMeetIt: "Library systems, archives, academic catalogues.",
    watchFor: "A field-and-subfield vocabulary going back to the 1960s. Domain knowledge matters more than parsing skill." },
  { name: "GTFS", group: "Web & interchange", effort: "Low",
    whatItIs: "Public transit schedules and, in the realtime variant, vehicle positions.",
    whereYouMeetIt: "Transit apps, municipal open data, mobility projects.",
    watchFor: "A zip of CSVs with a well-specified schema — one of the nicer standards you will meet." },
  { name: "DXF / DWG", group: "Engineering", effort: "High",
    whatItIs: "AutoCAD drawing interchange and native formats.",
    whereYouMeetIt: "Architecture, manufacturing, sign-making, fabrication.",
    watchFor: "DWG is proprietary and needs a licensed library. DXF is readable but loses fidelity." },
  { name: "IFC", group: "Engineering", effort: "High",
    whatItIs: "Building information modelling exchange.",
    whereYouMeetIt: "Construction, facilities management, BIM coordination.",
    watchFor: "Files are enormous and semantically rich. Specialist tooling, not a weekend parser." },
  { name: "STEP (ISO 10303)", group: "Engineering", effort: "High",
    whatItIs: "Neutral CAD geometry exchange.",
    whereYouMeetIt: "Manufacturing, CNC, supplier drawing packages.",
    watchFor: "Geometry survives, feature history does not. Set expectations about what \"we can import your CAD\" means." },
];

export const AUTH_GROUPS: string[] = ["Delegated authorisation", "Enterprise SSO", "Tokens & sessions", "Direct credentials", "Multi-factor", "Authorisation models"];

export const AUTH: AuthEntry[] = [
  { name: "OAuth 2.0", group: "Delegated authorisation", posture: "Use with care",
    whatItIs: "Delegated authorisation — lets an app act on a user's behalf without holding their password. It is not a login protocol, though it is constantly used as one.",
    whereYouMeetIt: "\"Connect your Google account\", \"Sign in with GitHub\", every third-party API integration.",
    watchFor: "The implicit flow and password grant are both dead. If a vendor's docs still show them, their platform is old." },
  { name: "OAuth 2.1", group: "Delegated authorisation", posture: "Safe",
    whatItIs: "OAuth 2.0 with the mistakes removed: PKCE mandatory, implicit and password grants gone, redirect URIs matched exactly.",
    whereYouMeetIt: "Anything new. Treat it as the baseline.",
    watchFor: "Exact redirect-URI matching bites on preview deployments — every Vercel preview URL needs registering or a proxy." },
  { name: "OpenID Connect", group: "Delegated authorisation", posture: "Safe",
    whatItIs: "An identity layer on top of OAuth 2.0. Adds the ID token, which actually says who the user is.",
    whereYouMeetIt: "The correct answer for \"let users sign in with their existing account\".",
    watchFor: "Validate the ID token signature, issuer, audience and expiry. Skipping any one of those is the classic hole." },
  { name: "PKCE", group: "Delegated authorisation", posture: "Safe",
    whatItIs: "Proof Key for Code Exchange — binds the authorisation code to the client that requested it.",
    whereYouMeetIt: "Mobile apps, SPAs, and now every OAuth flow under 2.1.",
    watchFor: "Not optional any more, even for confidential clients. Turn it on." },
  { name: "Authorization code flow", group: "Delegated authorisation", posture: "Safe",
    whatItIs: "The browser gets a short-lived code; the server swaps it for tokens out of band.",
    whereYouMeetIt: "Server-rendered apps and, with PKCE, everything else.",
    watchFor: "The code must be single-use and short-lived. Replay protection is on you if you built the server." },
  { name: "Client credentials flow", group: "Delegated authorisation", posture: "Safe",
    whatItIs: "Machine-to-machine tokens. No user involved.",
    whereYouMeetIt: "Backend jobs, scheduled syncs, service integrations.",
    watchFor: "The secret lands in an environment variable and stays there for years. Put rotation on the calendar at build time." },
  { name: "Refresh tokens", group: "Delegated authorisation", posture: "Use with care",
    whatItIs: "Long-lived credential used to mint new access tokens without re-prompting.",
    whereYouMeetIt: "Any integration that must keep working while nobody is watching.",
    watchFor: "Rotation with reuse detection is the modern pattern. A leaked non-rotating refresh token is a permanent breach." },
  { name: "SAML 2.0", group: "Enterprise SSO", posture: "Safe",
    whatItIs: "Signed XML assertions passed through the browser. The enterprise SSO standard.",
    whereYouMeetIt: "Selling to any company with an IT department. Okta, Entra ID, Ping, ADFS.",
    watchFor: "Signing certificates expire, usually at 2am on a Sunday. Monitor the expiry and automate the metadata refresh." },
  { name: "WS-Federation", group: "Enterprise SSO", posture: "Use with care",
    whatItIs: "Microsoft's older federation protocol, predating SAML's dominance.",
    whereYouMeetIt: "Legacy ADFS estates and older .NET applications.",
    watchFor: "Migrate to OIDC or SAML when you touch it. Tooling support is thinning out." },
  { name: "SCIM", group: "Enterprise SSO", posture: "Safe",
    whatItIs: "Standard REST API for provisioning and de-provisioning users from a directory.",
    whereYouMeetIt: "Enterprise customers who want staff removed from your app when they leave.",
    watchFor: "De-provisioning is the part that matters and the part that is usually broken. Test the leaver path explicitly." },
  { name: "Kerberos", group: "Enterprise SSO", posture: "Safe",
    whatItIs: "Ticket-granting authentication. What actually happens when a Windows user signs in.",
    whereYouMeetIt: "Domain-joined intranets, SQL Server integrated auth, on-premise SSO.",
    watchFor: "Clock skew over five minutes breaks everything. So does a missing SPN. Neither error message says so." },
  { name: "NTLM", group: "Enterprise SSO", posture: "Avoid",
    whatItIs: "Microsoft's pre-Kerberos challenge-response authentication.",
    whereYouMeetIt: "Old intranet apps, IIS sites, legacy file shares.",
    watchFor: "Vulnerable to relay attacks and being actively disabled by Microsoft. If you find it, that is a migration item." },
  { name: "LDAP bind", group: "Enterprise SSO", posture: "Use with care",
    whatItIs: "Authenticating by attempting a directory bind with the user's credentials.",
    whereYouMeetIt: "Older intranet applications wired straight to Active Directory.",
    watchFor: "Your app handles the raw password, which is exactly what SSO exists to avoid. Move to SAML or OIDC." },
  { name: "Entra ID (Azure AD)", group: "Enterprise SSO", posture: "Safe",
    whatItIs: "Microsoft's cloud identity platform — OIDC, SAML and Graph in one.",
    whereYouMeetIt: "Any Microsoft 365 client, which is most business clients.",
    watchFor: "App registration, admin consent and conditional access are three separate approvals. Start the conversation early." },
  { name: "Okta / Auth0", group: "Enterprise SSO", posture: "Safe",
    whatItIs: "Hosted identity providers covering OIDC, SAML, MFA and user management.",
    whereYouMeetIt: "Startups avoiding building auth, and enterprises standardising on one IdP.",
    watchFor: "Pricing steps up sharply at the enterprise tier, and the connection features you need are usually above the step." },
  { name: "JWT", group: "Tokens & sessions", posture: "Use with care",
    whatItIs: "A signed, self-contained token carrying claims. Readable by anyone holding it.",
    whereYouMeetIt: "API authentication, session state, service-to-service calls.",
    watchFor: "Never put anything secret in the payload — it is base64, not encryption. Reject `alg: none` and pin the algorithm." },
  { name: "JWKS", group: "Tokens & sessions", posture: "Safe",
    whatItIs: "A published endpoint of public keys used to verify tokens, allowing rotation without redeployment.",
    whereYouMeetIt: "Every OIDC provider exposes one.",
    watchFor: "Cache the key set but honour rotation. Fetching it on every request is a self-inflicted rate limit." },
  { name: "PASETO", group: "Tokens & sessions", posture: "Safe",
    whatItIs: "Platform-agnostic security tokens — JWT's design mistakes removed by fixing the algorithm per version.",
    whereYouMeetIt: "Greenfield systems whose authors have been bitten by JWT.",
    watchFor: "Better design, much smaller ecosystem. Check library support in your language before committing." },
  { name: "Server-side sessions", group: "Tokens & sessions", posture: "Safe",
    whatItIs: "An opaque cookie pointing at server-held state.",
    whereYouMeetIt: "Server-rendered apps, and still the right default for a browser-facing product.",
    watchFor: "Revocation actually works, which is more than JWT can say. Set HttpOnly, Secure and SameSite." },
  { name: "Magic links", group: "Tokens & sessions", posture: "Use with care",
    whatItIs: "Sign-in by emailed one-time link. No password to forget or leak.",
    whereYouMeetIt: "Client portals, low-frequency logins, consumer apps.",
    watchFor: "Your login is now hostage to email deliverability. Single-use, short expiry, and a fallback path." },
  { name: "HTTP Basic auth", group: "Direct credentials", posture: "Avoid",
    whatItIs: "Username and password base64-encoded in a header. Not encrypted.",
    whereYouMeetIt: "Internal tools, old APIs, device admin pages.",
    watchFor: "Only defensible over TLS on an internal network, and even then it is a finding waiting to be written up." },
  { name: "API keys", group: "Direct credentials", posture: "Use with care",
    whatItIs: "A static shared secret identifying the caller.",
    whereYouMeetIt: "Most vendor APIs, webhooks, internal service calls.",
    watchFor: "They leak into repos, logs and support tickets. Scope them, rotate them, and never put one in front-end code." },
  { name: "HMAC request signing", group: "Direct credentials", posture: "Safe",
    whatItIs: "Sign the request body and a timestamp with a shared secret.",
    whereYouMeetIt: "Stripe, AWS, and every webhook worth trusting.",
    watchFor: "Compare signatures in constant time and reject stale timestamps, or you have replay protection in name only." },
  { name: "mTLS", group: "Direct credentials", posture: "Safe",
    whatItIs: "Both sides present certificates. The strongest common option for machine-to-machine trust.",
    whereYouMeetIt: "Bank and payment integrations, service meshes, regulated data exchange.",
    watchFor: "Certificate lifecycle is the entire operational burden. Know who renews, and when, before go-live." },
  { name: "WebAuthn / passkeys", group: "Multi-factor", posture: "Safe",
    whatItIs: "Public-key authentication bound to the device and origin. Phishing-resistant by construction.",
    whereYouMeetIt: "Consumer apps, admin accounts, anything worth protecting properly.",
    watchFor: "Account recovery is the hard part. Design the lost-device path before you ship the happy path." },
  { name: "TOTP", group: "Multi-factor", posture: "Safe",
    whatItIs: "Six-digit codes from an authenticator app.",
    whereYouMeetIt: "The pragmatic second factor for most business applications.",
    watchFor: "Clock drift causes mystery failures. Accept a one-step window and store recovery codes." },
  { name: "SMS OTP", group: "Multi-factor", posture: "Use with care",
    whatItIs: "One-time codes by text message.",
    whereYouMeetIt: "Consumer flows where users will not install an app.",
    watchFor: "SIM-swap attacks are real and NIST discourages it. Better than nothing, worse than everything else here." },
  { name: "Push MFA", group: "Multi-factor", posture: "Use with care",
    whatItIs: "Approve-or-deny prompt on a registered phone.",
    whereYouMeetIt: "Enterprise estates on Okta, Duo or Entra.",
    watchFor: "MFA fatigue attacks work. Insist on number matching, which most providers now offer." },
  { name: "RBAC", group: "Authorisation models", posture: "Safe",
    whatItIs: "Permissions attached to named roles, users attached to roles.",
    whereYouMeetIt: "The default model for internal tools and most SaaS.",
    watchFor: "Roles multiply until nobody can say what \"Manager\" grants. Review the matrix annually or it rots." },
  { name: "ABAC", group: "Authorisation models", posture: "Use with care",
    whatItIs: "Decisions computed from attributes — department, location, record owner, time of day.",
    whereYouMeetIt: "Healthcare, government, anything with genuinely conditional access.",
    watchFor: "Far more expressive and far harder to audit. Only reach for it when RBAC has demonstrably failed." },
  { name: "Row-level security", group: "Authorisation models", posture: "Safe",
    whatItIs: "The database itself filters rows by the current user.",
    whereYouMeetIt: "Multi-tenant apps, client portals, Postgres and Supabase estates.",
    watchFor: "Isolation enforced where it cannot be bypassed by a forgotten `where` clause. Test with a second tenant, always." },
  { name: "Service accounts", group: "Authorisation models", posture: "Use with care",
    whatItIs: "Non-human identities for jobs and integrations.",
    whereYouMeetIt: "Scheduled syncs, CI pipelines, server-to-server work.",
    watchFor: "They accumulate permissions and outlive the person who created them. Inventory them during any audit." },
];

export const INFRA_GROUPS: string[] = ["Relational databases", "NoSQL & search", "Analytics & warehouse", "Managed platforms", "Web & app servers", "Hosting & runtime", "Integration & ETL"];

export const INFRA: InfraEntry[] = [
  { name: "PostgreSQL", group: "Relational databases", standing: "Current",
    whatItIs: "The default open-source relational database. Extensions cover JSON, geospatial, full-text, vectors and time series.",
    whereYouMeetIt: "Nearly every modern project, and the target of most migrations.",
    watchFor: "Rarely the wrong answer. If a client is choosing a database and has no constraint, this is it." },
  { name: "MySQL / MariaDB", group: "Relational databases", standing: "Current",
    whatItIs: "The other default. Ubiquitous on shared hosting and behind WordPress.",
    whereYouMeetIt: "LAMP estates, WooCommerce, older PHP applications.",
    watchFor: "Check the storage engine and character set — older installs on MyISAM or latin1 will surprise you with emoji and locks." },
  { name: "SQL Server", group: "Relational databases", standing: "Current",
    whatItIs: "Microsoft's relational engine, tightly coupled to Windows auth and the .NET stack.",
    whereYouMeetIt: "Any Microsoft-shop client, most mid-market ERPs.",
    watchFor: "Licensing is per core and expensive. Confirm the edition before proposing anything that needs more hardware." },
  { name: "Oracle Database", group: "Relational databases", standing: "Current",
    whatItIs: "The enterprise incumbent. Enormously capable, enormously licensed.",
    whereYouMeetIt: "Large ERP, banking, telco, government.",
    watchFor: "Never move data off it or add a read replica without the client's licensing people in the room." },
  { name: "IBM Db2", group: "Relational databases", standing: "Legacy",
    whatItIs: "IBM's relational engine, on mainframe (z/OS), IBM i, and Linux.",
    whereYouMeetIt: "Banking, insurance, IBM i shops.",
    watchFor: "Db2 for i and Db2 LUW are different products with different tooling. Establish which one before quoting." },
  { name: "SQLite", group: "Relational databases", standing: "Current",
    whatItIs: "A whole relational database in one file, in-process.",
    whereYouMeetIt: "Mobile apps, desktop software, edge caches, and increasingly small production sites.",
    watchFor: "One writer at a time. Fine for most workloads, fatal for the one that needs concurrent writes." },
  { name: "Microsoft Access", group: "Relational databases", standing: "Legacy",
    whatItIs: "A desktop database plus forms plus reports in a single file on a share drive.",
    whereYouMeetIt: "Departmental systems that quietly became the system of record.",
    watchFor: "Corruption with multiple users is routine and backups usually do not exist. Migrating one is a rescue operation." },
  { name: "Firebird / InterBase", group: "Relational databases", standing: "Legacy",
    whatItIs: "Long-lived embedded-capable relational engine.",
    whereYouMeetIt: "Delphi applications, point-of-sale, European vertical software.",
    watchFor: "Small talent pool. Budget discovery time; documentation is thin and often not in English." },
  { name: "Sybase ASE", group: "Relational databases", standing: "Legacy",
    whatItIs: "SQL Server's ancestor, now SAP's.",
    whereYouMeetIt: "Finance and trading systems that never migrated.",
    watchFor: "T-SQL dialects have diverged. A SQL Server migration is not the copy-paste job it looks like." },
  { name: "Informix", group: "Relational databases", standing: "Legacy",
    whatItIs: "IBM's other relational engine, strong in retail and telemetry.",
    whereYouMeetIt: "Retail chains, older logistics and utility systems.",
    watchFor: "Often paired with Informix 4GL applications. Replacing the database means replacing the app." },
  { name: "FoxPro / dBase", group: "Relational databases", standing: "Legacy",
    whatItIs: "File-based desktop databases from the DOS era.",
    whereYouMeetIt: "Dental, legal, small retail and municipal software still running on Windows.",
    watchFor: "Unsupported since 2015. This is a stability risk to raise in writing, not a preference." },
  { name: "Btrieve / Pervasive / Actian Zen", group: "Relational databases", standing: "Legacy",
    whatItIs: "Transactional key-value engine embedded in vertical applications.",
    whereYouMeetIt: "Manufacturing, distribution and accounting packages.",
    watchFor: "Usually reachable only through the vendor's ODBC driver. Direct file access is a trap." },
  { name: "Adabas", group: "Relational databases", standing: "Legacy",
    whatItIs: "Software AG's high-performance mainframe database, paired with Natural.",
    whereYouMeetIt: "Insurance, government, utilities.",
    watchFor: "Extraction goes through EntireX or a nightly unload. Real-time access is generally not on offer." },
  { name: "IMS / VSAM", group: "Relational databases", standing: "Legacy",
    whatItIs: "IBM's hierarchical database and indexed file system. Pre-relational.",
    whereYouMeetIt: "Core banking and insurance on z/OS.",
    watchFor: "No SQL layer without a gateway product. Assume batch extract, not query." },
  { name: "InterSystems IRIS / Caché", group: "Relational databases", standing: "Current",
    whatItIs: "Multi-model database with MUMPS heritage, dominant in healthcare.",
    whereYouMeetIt: "Epic, hospital systems, health information exchanges.",
    watchFor: "Globals and SQL are two views of the same data. Learn which one the client's team actually uses." },
  { name: "MongoDB", group: "NoSQL & search", standing: "Current",
    whatItIs: "Document database with flexible schemas.",
    whereYouMeetIt: "Content systems, event stores, prototypes that became production.",
    watchFor: "Schema flexibility is a debt instrument. Ask what enforces shape — usually nothing does." },
  { name: "Redis / Valkey", group: "NoSQL & search", standing: "Current",
    whatItIs: "In-memory key-value store used for cache, sessions, queues and rate limits.",
    whereYouMeetIt: "Almost every production web app at some scale.",
    watchFor: "Confirm persistence settings. Plenty of teams learn their \"database\" was volatile during an outage." },
  { name: "Elasticsearch / OpenSearch", group: "NoSQL & search", standing: "Current",
    whatItIs: "Distributed search and log analytics.",
    whereYouMeetIt: "Site search, log aggregation, observability platforms.",
    watchFor: "Operationally demanding and expensive at rest. For simple site search, Postgres full-text is often enough." },
  { name: "Neo4j", group: "NoSQL & search", standing: "Current",
    whatItIs: "Property graph database queried with Cypher.",
    whereYouMeetIt: "Fraud rings, recommendations, org and network hierarchies.",
    watchFor: "Justified when traversal depth is the point. For two joins, use a relational database." },
  { name: "Cassandra / ScyllaDB", group: "NoSQL & search", standing: "Current",
    whatItIs: "Wide-column store built for write throughput and multi-region availability.",
    whereYouMeetIt: "Telemetry, messaging, very large time-series estates.",
    watchFor: "Query patterns must be known before the schema. Retro-fitting a new access path is a data migration." },
  { name: "DynamoDB", group: "NoSQL & search", standing: "Current",
    whatItIs: "AWS's managed key-value and document store with predictable latency.",
    whereYouMeetIt: "Serverless architectures on AWS.",
    watchFor: "Single-table design is powerful and unforgiving. Get the access patterns down on paper first." },
  { name: "Snowflake", group: "Analytics & warehouse", standing: "Current",
    whatItIs: "Cloud data warehouse separating storage from compute.",
    whereYouMeetIt: "Mid-market and enterprise analytics, BI back-ends.",
    watchFor: "Compute bills by the second while a warehouse is warm. Auto-suspend is the single biggest cost control." },
  { name: "BigQuery", group: "Analytics & warehouse", standing: "Current",
    whatItIs: "Google's serverless warehouse, billed largely by bytes scanned.",
    whereYouMeetIt: "Google-centric estates, GA4 exports, ad-tech data.",
    watchFor: "`SELECT *` on a wide table is a line item. Partition, cluster, and select columns explicitly." },
  { name: "Redshift", group: "Analytics & warehouse", standing: "Current",
    whatItIs: "AWS's columnar warehouse.",
    whereYouMeetIt: "AWS-native analytics stacks.",
    watchFor: "Vacuum and distribution keys still matter. Less hands-off than Snowflake or BigQuery." },
  { name: "ClickHouse", group: "Analytics & warehouse", standing: "Current",
    whatItIs: "Extremely fast columnar analytics database.",
    whereYouMeetIt: "Product analytics, observability, real-time dashboards.",
    watchFor: "Excellent at aggregation, poor at updates and deletes. Model it as append-only." },
  { name: "DuckDB", group: "Analytics & warehouse", standing: "Current",
    whatItIs: "In-process analytical database — SQLite's shape, columnar engine.",
    whereYouMeetIt: "Local analysis, embedded reporting, querying Parquet directly.",
    watchFor: "Often removes the need for a warehouse entirely on datasets under a few hundred gigabytes." },
  { name: "Supabase", group: "Managed platforms", standing: "Current",
    whatItIs: "Managed Postgres with auth, storage, realtime and row-level security.",
    whereYouMeetIt: "Small-team products that need a real database without an ops function.",
    watchFor: "RLS is the security model. If it is off, every client-side key is a full-database key." },
  { name: "Firebase", group: "Managed platforms", standing: "Current",
    whatItIs: "Google's app backend — Firestore, auth, functions, hosting.",
    whereYouMeetIt: "Mobile apps, prototypes, Flutter projects.",
    watchFor: "Security rules are the entire access model and are easy to get wrong. Read costs scale with careless queries." },
  { name: "PlanetScale / Neon", group: "Managed platforms", standing: "Current",
    whatItIs: "Serverless MySQL and Postgres with branching workflows.",
    whereYouMeetIt: "Teams wanting database branches to match git branches.",
    watchFor: "Connection limits and pooling behaviour differ from a normal instance. Check your ORM's expectations." },
  { name: "Apache httpd", group: "Web & app servers", standing: "Current",
    whatItIs: "The venerable web server. Module-rich, .htaccess-driven.",
    whereYouMeetIt: "Shared hosting, cPanel, older PHP deployments.",
    watchFor: "Per-request .htaccess lookups cost performance. Move rules into the main config where you can." },
  { name: "Nginx", group: "Web & app servers", standing: "Current",
    whatItIs: "Event-driven web server, reverse proxy and load balancer.",
    whereYouMeetIt: "Most modern Linux deployments, in front of nearly everything.",
    watchFor: "Config is order-sensitive in ways that surprise people. `location` matching rules repay ten minutes of reading." },
  { name: "Caddy", group: "Web & app servers", standing: "Current",
    whatItIs: "Web server with automatic HTTPS certificates out of the box.",
    whereYouMeetIt: "Small deployments and internal services where TLS admin is the annoyance.",
    watchFor: "Genuinely removes a whole class of certificate work. Underrated for internal tools." },
  { name: "IIS", group: "Web & app servers", standing: "Current",
    whatItIs: "Microsoft's web server, integrated with Windows auth and .NET.",
    whereYouMeetIt: "Any Windows-hosted application, most on-premise .NET.",
    watchFor: "Application pool identity and recycling settings cause most \"it works then stops\" reports." },
  { name: "Tomcat / Jetty", group: "Web & app servers", standing: "Current",
    whatItIs: "Java servlet containers.",
    whereYouMeetIt: "Spring applications, older Java web apps, vendor appliances.",
    watchFor: "Version and JDK level travel together. Check both before proposing an upgrade." },
  { name: "WildFly / JBoss", group: "Web & app servers", standing: "Legacy",
    whatItIs: "Full Java EE application server.",
    whereYouMeetIt: "Enterprise Java estates from the 2000s.",
    watchFor: "Deployment descriptors and datasource config live in the server, not the app. Nothing is portable by accident." },
  { name: "WebLogic", group: "Web & app servers", standing: "Legacy",
    whatItIs: "Oracle's Java application server.",
    whereYouMeetIt: "Oracle-centric enterprises, older ERP front-ends.",
    watchFor: "Licensed, heavy, and usually managed by a team you will need to book time with." },
  { name: "WebSphere", group: "Web & app servers", standing: "Legacy",
    whatItIs: "IBM's Java application server.",
    whereYouMeetIt: "Banking and insurance Java estates.",
    watchFor: "Traditional WebSphere and Liberty are very different. Find out which is actually running." },
  { name: "Gunicorn / uWSGI", group: "Web & app servers", standing: "Current",
    whatItIs: "Python WSGI application servers, run behind Nginx.",
    whereYouMeetIt: "Django and Flask deployments.",
    watchFor: "Worker count and timeout defaults are wrong for most workloads. Tune them or watch requests die at 30 seconds." },
  { name: "Docker", group: "Hosting & runtime", standing: "Current",
    whatItIs: "Container packaging and runtime.",
    whereYouMeetIt: "Nearly every deployment pipeline built in the last decade.",
    watchFor: "A container is not a security boundary by default. Do not run as root, and pin base image versions." },
  { name: "Kubernetes", group: "Hosting & runtime", standing: "Current",
    whatItIs: "Container orchestration across a cluster.",
    whereYouMeetIt: "Larger estates, platform teams, anything multi-service at scale.",
    watchFor: "Real operational weight. For a studio-sized project it is almost always more machine than the problem needs." },
  { name: "Vercel", group: "Hosting & runtime", standing: "Current",
    whatItIs: "Managed hosting for Next.js and front-end frameworks, with edge functions and previews.",
    whereYouMeetIt: "Modern JS deployments, marketing sites, dashboards.",
    watchFor: "No cron on the platform — scheduled work runs from GitHub Actions or an external trigger." },
  { name: "Netlify", group: "Hosting & runtime", standing: "Current",
    whatItIs: "Static and Jamstack hosting with functions and forms.",
    whereYouMeetIt: "Marketing sites, Astro and Hugo builds.",
    watchFor: "Build-minute limits bite on large sites with frequent deploys." },
  { name: "Cloudflare Workers", group: "Hosting & runtime", standing: "Current",
    whatItIs: "Edge compute with KV, D1, R2 and Durable Objects alongside.",
    whereYouMeetIt: "Low-latency APIs, edge middleware, small full-stack services.",
    watchFor: "Not Node. Check library compatibility before committing — a lot of npm packages simply will not run." },
  { name: "AWS Lambda", group: "Hosting & runtime", standing: "Current",
    whatItIs: "Event-driven serverless functions.",
    whereYouMeetIt: "Glue code, scheduled jobs, event processing on AWS.",
    watchFor: "Cold starts and VPC attachment latency are the two things that surprise people in production." },
  { name: "Heroku", group: "Hosting & runtime", standing: "Legacy",
    whatItIs: "The original platform-as-a-service.",
    whereYouMeetIt: "Rails and Django apps deployed between 2012 and 2020.",
    watchFor: "Free tier gone, pricing risen. Many clients on it are quietly overpaying for a dyno they could move." },
  { name: "cPanel / Plesk", group: "Hosting & runtime", standing: "Legacy",
    whatItIs: "Shared-hosting control panels.",
    whereYouMeetIt: "Small business WordPress and PHP sites.",
    watchFor: "Deployment is often by FTP with no version control. Fixing that is usually step one of any engagement." },
  { name: "IBM i (AS/400)", group: "Hosting & runtime", standing: "Legacy",
    whatItIs: "IBM's integrated midrange platform — OS, database and application stack in one.",
    whereYouMeetIt: "Manufacturing, distribution, wholesale.",
    watchFor: "Extremely reliable and extremely opaque from outside. Integration goes through IWS, ODBC or a nightly extract." },
  { name: "z/OS mainframe", group: "Hosting & runtime", standing: "Legacy",
    whatItIs: "IBM's mainframe operating system running CICS, batch and Db2.",
    whereYouMeetIt: "Banking, insurance, government, large retail.",
    watchFor: "Access is granted by a team, not a password. Timeline is governed by their change window, not yours." },
  { name: "VMware / Hyper-V", group: "Hosting & runtime", standing: "Current",
    whatItIs: "On-premise virtualisation.",
    whereYouMeetIt: "Client-owned server rooms and colocation racks.",
    watchFor: "Broadcom's VMware licensing changes have pushed real migrations. Worth asking about at renewal time." },
  { name: "Kafka", group: "Integration & ETL", standing: "Current",
    whatItIs: "Distributed, replayable event log.",
    whereYouMeetIt: "Event-driven architectures, change-data-capture, analytics ingestion.",
    watchFor: "Heavy to run yourself. Managed (Confluent, MSK, Redpanda) is usually the honest option." },
  { name: "RabbitMQ", group: "Integration & ETL", standing: "Current",
    whatItIs: "Traditional message broker with flexible routing.",
    whereYouMeetIt: "Job queues, work distribution, service decoupling.",
    watchFor: "Simpler than Kafka and right far more often. Reach for it first." },
  { name: "IBM MQ", group: "Integration & ETL", standing: "Legacy",
    whatItIs: "The enterprise message broker of record in banking and insurance.",
    whereYouMeetIt: "Mainframe-adjacent integration, financial messaging.",
    watchFor: "Queue definitions and channel security are managed centrally. You will be requesting, not configuring." },
  { name: "BizTalk", group: "Integration & ETL", standing: "Legacy",
    whatItIs: "Microsoft's integration server — mapping, orchestration, EDI, adapters.",
    whereYouMeetIt: "Mid-2000s Microsoft enterprises still exchanging EDI.",
    watchFor: "Extended support ends 2028 and there is no direct successor. Any BizTalk estate is a migration conversation." },
  { name: "MuleSoft", group: "Integration & ETL", standing: "Current",
    whatItIs: "API-led integration platform, now Salesforce's.",
    whereYouMeetIt: "Large enterprises with an API strategy and the budget for one.",
    watchFor: "Licensing is a board-level number. Confirm the client already owns it before designing around it." },
  { name: "Boomi", group: "Integration & ETL", standing: "Current",
    whatItIs: "Cloud integration platform, lighter than MuleSoft.",
    whereYouMeetIt: "Mid-market ERP, CRM and finance system integration.",
    watchFor: "Connector coverage is good; custom logic inside it is harder to version and review than code." },
  { name: "SSIS", group: "Integration & ETL", standing: "Legacy",
    whatItIs: "SQL Server Integration Services — Microsoft's ETL tool.",
    whereYouMeetIt: "Anywhere SQL Server is the warehouse.",
    watchFor: "Packages are stored as XML and are painful to diff. Treat them as artefacts, not source." },
  { name: "Talend / Informatica", group: "Integration & ETL", standing: "Current",
    whatItIs: "Enterprise ETL and data integration suites.",
    whereYouMeetIt: "Large data estates with a dedicated integration team.",
    watchFor: "Licence and specialist staffing costs dwarf the build. Not studio-scale tooling." },
  { name: "Fivetran / Airbyte", group: "Integration & ETL", standing: "Current",
    whatItIs: "Managed connectors that replicate SaaS and database sources into a warehouse.",
    whereYouMeetIt: "Getting client data somewhere analysable without writing extract code.",
    watchFor: "Fivetran bills on changed rows and can spike unexpectedly. Airbyte connector quality varies by source." },
  { name: "dbt", group: "Integration & ETL", standing: "Current",
    whatItIs: "Version-controlled, tested SQL transformations inside the warehouse.",
    whereYouMeetIt: "Any analytics stack with more than a handful of models.",
    watchFor: "The right home for business logic that currently lives in twenty saved queries and someone's head." },
  { name: "Zapier / Make / n8n", group: "Integration & ETL", standing: "Current",
    whatItIs: "No-code and low-code automation between SaaS tools.",
    whereYouMeetIt: "Small business workflows, and the honest answer for low-volume glue.",
    watchFor: "Per-task pricing beats a build until volume rises, then reverses sharply. Model both before recommending." },
  { name: "Power Automate", group: "Integration & ETL", standing: "Current",
    whatItIs: "Microsoft's workflow automation across 365 and Dynamics.",
    whereYouMeetIt: "Microsoft-shop clients who already pay for it.",
    watchFor: "Often already licensed and unused. Check before proposing a paid alternative." },
  { name: "Apache Airflow", group: "Integration & ETL", standing: "Current",
    whatItIs: "Scheduled workflow orchestration with retries, backfills and a failure UI.",
    whereYouMeetIt: "Data pipelines with real dependencies between steps.",
    watchFor: "Overkill below roughly a dozen jobs. GitHub Actions covers the small end perfectly well." },
];

export const STACK_GROUPS: string[] = ["Classic server-rendered", "Enterprise", "Modern full-stack JS", "Mobile", "E-commerce & CMS", "Data & AI", "Serverless & edge"];

export const STACKS: StackEntry[] = [
  { name: "LAMP", group: "Classic server-rendered", standing: "Legacy",
    frontEnd: "Server-rendered PHP / jQuery", backEnd: "PHP on Apache",
    data: "MySQL", hosting: "Shared hosting, cPanel, single VPS",
    bestFor: "WordPress, WooCommerce and the long tail of small business sites. Cheapest hosting on earth and every host supports it.",
    watchOutFor: "Deployment is often FTP with no version control. Fixing that is usually the first real task of any engagement." },
  { name: "LEMP", group: "Classic server-rendered", standing: "Current",
    frontEnd: "Server-rendered PHP / Alpine", backEnd: "PHP-FPM on Nginx",
    data: "MySQL or PostgreSQL", hosting: "VPS, Docker, managed PHP hosts",
    bestFor: "Modern PHP done properly — Laravel and Symfony applications that need to handle real traffic.",
    watchOutFor: "Nginx will not read .htaccess. Rewrite rules from a LAMP site must be ported by hand." },
  { name: "Rails + Postgres + Hotwire", group: "Classic server-rendered", standing: "Current",
    frontEnd: "Hotwire (Turbo + Stimulus)", backEnd: "Ruby on Rails",
    data: "PostgreSQL", hosting: "Fly.io, Render, Heroku, Kamal on a VPS",
    bestFor: "CRUD-heavy products built fast by a small team. Still one of the highest output-per-developer stacks in existence.",
    watchOutFor: "Hiring pool is thinner than it was. Confirm who maintains it after handoff." },
  { name: "Django + Postgres + HTMX", group: "Classic server-rendered", standing: "Current",
    frontEnd: "HTMX + server-rendered templates", backEnd: "Django",
    data: "PostgreSQL", hosting: "Render, Fly.io, VPS, App Platform",
    bestFor: "Admin-heavy internal tools and portals. Django admin alone can be most of the deliverable.",
    watchOutFor: "HTMX keeps you out of a front-end build — right up until the client asks for something genuinely app-like." },
  { name: "Laravel TALL", group: "Classic server-rendered", standing: "Current",
    frontEnd: "Tailwind + Alpine.js", backEnd: "Laravel + Livewire",
    data: "MySQL or PostgreSQL", hosting: "Forge, Vapor, Ploi, VPS",
    bestFor: "Interactive PHP apps without writing an API or a JavaScript build. Very fast for form-heavy business software.",
    watchOutFor: "Livewire round-trips to the server on interaction. Latency shows on slow connections." },
  { name: "ASP.NET Core + SQL Server", group: "Enterprise", standing: "Current",
    frontEnd: "Razor Pages, Blazor, or React", backEnd: "ASP.NET Core",
    data: "SQL Server", hosting: "Azure App Service, IIS on-premise",
    bestFor: "Microsoft-shop clients. Entra ID sign-in, existing DBA team, existing licences.",
    watchOutFor: "SQL Server licensing is per core. Scaling out is a procurement decision, not an infrastructure one." },
  { name: "Spring Boot + Postgres + React", group: "Enterprise", standing: "Current",
    frontEnd: "React or Angular", backEnd: "Spring Boot (Java or Kotlin)",
    data: "PostgreSQL or Oracle", hosting: "Kubernetes, EC2, on-premise",
    bestFor: "Enterprises with an existing Java team and governance that expects the JVM.",
    watchOutFor: "Heavier ceremony than the project usually needs. Justified by the client's staff, not by the requirements." },
  { name: "MEAN / MERN", group: "Modern full-stack JS", standing: "Legacy",
    frontEnd: "Angular or React SPA", backEnd: "Express on Node.js",
    data: "MongoDB", hosting: "VPS, Heroku, Render",
    bestFor: "The 2015-era default. You will inherit these, rarely start one.",
    watchOutFor: "Client-rendered SPA plus schemaless documents is a hard combination to keep correct as a team changes." },
  { name: "PERN", group: "Modern full-stack JS", standing: "Current",
    frontEnd: "React SPA", backEnd: "Express or Fastify",
    data: "PostgreSQL", hosting: "Render, Fly.io, Railway, VPS",
    bestFor: "MERN's sensible sibling — same team skills, a database that enforces shape.",
    watchOutFor: "Still two deployables and two type systems unless you add tRPC or a shared schema package." },
  { name: "T3", group: "Modern full-stack JS", standing: "Current",
    frontEnd: "Next.js + Tailwind", backEnd: "tRPC + Prisma or Drizzle",
    data: "PostgreSQL", hosting: "Vercel + a managed Postgres",
    bestFor: "Typed end to end with no hand-written API layer. Excellent for a solo builder or a pair.",
    watchOutFor: "tRPC assumes one TypeScript codebase. The moment a mobile app or third party needs the API, you are writing REST anyway." },
  { name: "Next.js + Supabase", group: "Modern full-stack JS", standing: "Current",
    frontEnd: "Next.js App Router + Tailwind + shadcn/ui", backEnd: "Server actions and route handlers",
    data: "Postgres with row-level security", hosting: "Vercel + Supabase",
    bestFor: "Portals, dashboards and multi-tenant tools. Auth, storage, realtime and RLS arrive on day one.",
    watchOutFor: "RLS is the security model. If it is off on any table, the anon key is a full-database key." },
  { name: "Astro + headless CMS", group: "Modern full-stack JS", standing: "Current",
    frontEnd: "Astro islands", backEnd: "Static build, plus functions where needed",
    data: "Sanity, Payload, Contentful or Markdown", hosting: "Netlify, Vercel, Cloudflare Pages",
    bestFor: "Marketing and content sites where speed and SEO are the deliverable.",
    watchOutFor: "Rebuild times grow with page count. Above a few thousand pages, plan incremental builds." },
  { name: "SvelteKit + Postgres", group: "Modern full-stack JS", standing: "Current",
    frontEnd: "Svelte", backEnd: "SvelteKit endpoints",
    data: "PostgreSQL", hosting: "Vercel, Cloudflare, Node adapter on a VPS",
    bestFor: "Small, fast apps by developers who value less framework overhead.",
    watchOutFor: "Smaller ecosystem and hiring pool than React. Fine in-house, a consideration on handoff." },
  { name: "Phoenix LiveView", group: "Modern full-stack JS", standing: "Current",
    frontEnd: "LiveView (server-rendered, socket-driven)", backEnd: "Elixir + Phoenix",
    data: "PostgreSQL", hosting: "Fly.io, Gigalixir, VPS",
    bestFor: "Real-time interfaces without a front-end framework. Presence, chat and live dashboards are nearly free.",
    watchOutFor: "Every user holds an open connection with server-side state. Cheap on the BEAM, alien to most ops teams." },
  { name: "Go + Postgres + HTMX", group: "Modern full-stack JS", standing: "Current",
    frontEnd: "HTMX + templates", backEnd: "Go (net/http, Chi or Echo)",
    data: "PostgreSQL", hosting: "Single binary on a VPS, Fly.io, Cloud Run",
    bestFor: "Services that must be fast, small and boring. Deployment is one file.",
    watchOutFor: "Less framework means more decisions. Fine for a strong team, slow for a junior one." },
  { name: "Expo + Supabase", group: "Mobile", standing: "Current",
    frontEnd: "React Native via Expo", backEnd: "Supabase (Postgres, auth, storage)",
    data: "PostgreSQL with RLS", hosting: "EAS Build + Supabase",
    bestFor: "Cross-platform apps with over-the-air updates and web skills reused. The default studio mobile stack.",
    watchOutFor: "App-store review still gates native module changes. OTA covers JavaScript, not everything." },
  { name: "Flutter + Firebase", group: "Mobile", standing: "Current",
    frontEnd: "Flutter", backEnd: "Cloud Functions",
    data: "Firestore", hosting: "Firebase Hosting + Google Cloud",
    bestFor: "Highly custom UI, consistent rendering on cheap Android hardware, fast to a demo.",
    watchOutFor: "Firestore security rules are the whole access model, and reads bill per document. Careless queries cost real money." },
  { name: "Kotlin Multiplatform + Ktor", group: "Mobile", standing: "Current",
    frontEnd: "Compose Multiplatform or native UI", backEnd: "Ktor",
    data: "PostgreSQL", hosting: "JVM host, Kubernetes, cloud run",
    bestFor: "Sharing business logic across Android, iOS and back-end while keeping native UI.",
    watchOutFor: "Toolchain still moves quickly. Budget for churn on upgrades." },
  { name: "Shopify + custom theme", group: "E-commerce & CMS", standing: "Current",
    frontEnd: "Liquid theme or Hydrogen", backEnd: "Shopify platform + apps",
    data: "Shopify-managed", hosting: "Shopify",
    bestFor: "Real retail volume. Tax, fraud, fulfilment and payments are somebody else's problem.",
    watchOutFor: "Platform fees plus app subscriptions add up. Model total cost before comparing to a custom build." },
  { name: "WordPress + WooCommerce", group: "E-commerce & CMS", standing: "Legacy",
    frontEnd: "PHP theme", backEnd: "WordPress + plugins",
    data: "MySQL", hosting: "Managed WP host, cPanel",
    bestFor: "Clients who insist on editing everything themselves and already know the admin.",
    watchOutFor: "Plugin sprawl is the maintenance liability. Every plugin is an update, a vulnerability and a support call." },
  { name: "Headless commerce", group: "E-commerce & CMS", standing: "Current",
    frontEnd: "Next.js or Astro storefront", backEnd: "Shopify Storefront API, Medusa or Commerce Layer",
    data: "Platform-managed", hosting: "Vercel or Netlify + platform",
    bestFor: "Brand-led storefronts that need a custom experience over reliable commerce plumbing.",
    watchOutFor: "You now own the storefront's bugs and the platform's limits. More control, more surface." },
  { name: "Payload + Next.js", group: "E-commerce & CMS", standing: "Current",
    frontEnd: "Next.js", backEnd: "Payload CMS in the same app",
    data: "PostgreSQL or MongoDB", hosting: "Vercel, Render, VPS",
    bestFor: "Content sites where you want the CMS self-hosted, in-repo, with no per-seat pricing.",
    watchOutFor: "You are running the CMS. Upgrades and backups are yours, not a vendor's." },
  { name: "FastAPI + Postgres + React", group: "Data & AI", standing: "Current",
    frontEnd: "React or Next.js", backEnd: "FastAPI",
    data: "PostgreSQL (often + pgvector)", hosting: "Render, Fly.io, Cloud Run, ECS",
    bestFor: "Products where the interesting work is Python — models, retrieval, scientific computation.",
    watchOutFor: "Two deployables and two type systems. Generate the client from the OpenAPI spec rather than hand-writing it." },
  { name: "Next.js + AI SDK + pgvector", group: "Data & AI", standing: "Current",
    frontEnd: "Next.js streaming UI", backEnd: "Vercel AI SDK, route handlers",
    data: "Postgres with pgvector", hosting: "Vercel + managed Postgres",
    bestFor: "LLM products with a chat or assistant surface, built by a web team.",
    watchOutFor: "Token cost per request is a product decision. Set a ceiling before launch, not after the first bill." },
  { name: "Python + Airflow + Snowflake", group: "Data & AI", standing: "Current",
    frontEnd: "Metabase, Power BI or a custom dashboard", backEnd: "Airflow or Dagster + dbt",
    data: "Snowflake or BigQuery", hosting: "Managed Airflow + warehouse",
    bestFor: "Scheduled data work with real dependencies, feeding reporting people actually use.",
    watchOutFor: "Warehouse compute bills while warm. Auto-suspend and query review are the cost controls that matter." },
  { name: "Serverless AWS", group: "Serverless & edge", standing: "Current",
    frontEnd: "React SPA or Next.js", backEnd: "Lambda + API Gateway",
    data: "DynamoDB or Aurora Serverless", hosting: "AWS, deployed with SAM or CDK",
    bestFor: "Spiky, event-driven workloads where paying nothing at idle matters.",
    watchOutFor: "Local development and debugging are markedly worse. Cold starts and VPC attachment latency are real." },
  { name: "Cloudflare edge stack", group: "Serverless & edge", standing: "Current",
    frontEnd: "Astro, Next.js or Remix on Pages", backEnd: "Workers",
    data: "D1, KV, R2, Durable Objects", hosting: "Cloudflare",
    bestFor: "Globally low-latency APIs and small full-stack services, with generous free tiers.",
    watchOutFor: "Workers are not Node. Verify every dependency runs there before committing to it." },
  { name: "Static + forms service", group: "Serverless & edge", standing: "Current",
    frontEnd: "Astro, Hugo or plain HTML", backEnd: "Netlify Forms, Formspree or a single function",
    data: "None", hosting: "Netlify, Cloudflare Pages, S3 + CloudFront",
    bestFor: "Brochure sites. Nothing to patch, nothing to breach, pennies to host.",
    watchOutFor: "The correct answer far more often than clients expect. Say so before quoting a CMS." },
];

/** Tailwind tint per posture / effort / standing — one vocabulary, three scales. */
export const TONE: Record<string, string> = {
  Safe: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
  Low: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
  Current: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
  "Use with care": "bg-gold-bright/15 text-gold-bright border-gold-bright/30",
  Medium: "bg-gold-bright/15 text-gold-bright border-gold-bright/30",
  Avoid: "bg-rose-500/12 text-rose-400 border-rose-500/25",
  High: "bg-rose-500/12 text-rose-400 border-rose-500/25",
  Legacy: "bg-rose-500/12 text-rose-400 border-rose-500/25",
};
