// Brand marks for the Build Atlas.
//
// MARKS ships EMPTY on purpose. The atlas renders styled lettermarks until it
// is populated, which keeps ~60 KB of generated SVG path data out of the repo
// and out of every reviewer's diff. The prebuild step populates it on every
// build:
//
//   node scripts/build-stack-marks.mjs
//
// That rewrites the MARKS constant below in place, from the Simple Icons
// package (CC0-1.0). Re-run it whenever MARK_FOR changes. Nothing else in the
// app needs to change — Mark() already falls back cleanly when a key is absent.

export interface BrandMark {
  /** SVG path data, drawn in a 24x24 viewBox. */
  path: string;
  /** Official brand hex, without the leading #. */
  hex: string;
  title: string;
}

/* MARKS:START — generated, do not edit by hand */
export const MARKS: Record<string, BrandMark> = {};
/* MARKS:END */

/**
 * Display name to Simple Icons slug. Hand-maintained: this is the judgement
 * call ("Rails" is the `rubyonrails` mark, "Anchor" borrows Rust's), and it is
 * the input the build script reads. A name absent here renders as a lettermark,
 * which is the correct outcome for unbranded things like Structured Text.
 */
export const MARK_FOR: Record<string, string> = {
  "ABAP": "sap",
  "ASP.NET Core": "dotnet",
  "Ada": "ada",
  "Airflow / Dagster + Pandas": "apacheairflow",
  "Anchor (Solana)": "rust",
  "AppleScript": "apple",
  "Arduino (C++ subset)": "arduino",
  "Arduino / ESP-IDF + MQTT": "arduino",
  "Assembly (x86-64 / ARM)": "arm",
  "Astro": "astro",
  "Astro + Sanity": "astro",
  "Axum / Actix Web": "rust",
  "Bash / sh": "gnubash",
  "C": "c",
  "C# (Unity)": "unity",
  "C++": "cplusplus",
  "C++ (Unreal)": "unrealengine",
  "CUDA": "nvidia",
  "Carbon": "google",
  "Chisel": "scala",
  "Clojure": "clojure",
  "Clojure (ClojureScript)": "clojure",
  "Cloud Functions / Lambda": "python",
  "CoffeeScript": "coffeescript",
  "Common Lisp": "commonlisp",
  "Crystal": "crystal",
  "Cypher": "neo4j",
  "D": "d",
  "Dart": "dart",
  "Delphi / Object Pascal": "delphi",
  "Direct replication to PostgreSQL": "postgresql",
  "Django": "django",
  "Django admin": "django",
  "Dockerfile": "docker",
  "Elixir": "elixir",
  "Elm": "elm",
  "Embassy / embedded-hal": "rust",
  "Erlang": "erlang",
  "F#": "fsharp",
  "FastAPI": "fastapi",
  "FastAPI + LangChain / LlamaIndex": "fastapi",
  "FastAPI as an anti-corruption layer": "fastapi",
  "Fish": "fishshell",
  "Flutter": "flutter",
  "Flutter (Dart)": "flutter",
  "Flutter + Drift": "flutter",
  "Fortran": "fortran",
  "Foundry / Hardhat": "ethereum",
  "GDScript": "godotengine",
  "GLSL": "opengl",
  "Gin / Chi": "go",
  "GitHub Actions + Node": "githubactions",
  "GitHub Actions + Node scripts": "githubactions",
  "Gleam": "gleam",
  "Go": "go",
  "Godot": "godotengine",
  "GraphQL": "graphql",
  "Groovy": "apachegroovy",
  "HCL (Terraform)": "terraform",
  "Hack": "meta",
  "Haskell": "haskell",
  "Haxe": "haxe",
  "Hono / Fastify": "hono",
  "JRuby": "ruby",
  "JSON": "json",
  "Java": "openjdk",
  "Java (Android)": "android",
  "JavaScript": "javascript",
  "Julia": "julia",
  "Jython": "python",
  "K / q (kdb+)": "kx",
  "Kotlin": "kotlin",
  "Kotlin Multiplatform": "kotlin",
  "LabVIEW (G)": "labview",
  "Ladder Logic (IEC 61131-3)": "siemens",
  "Laravel + Cashier": "laravel",
  "Laravel + Cashier Connect": "laravel",
  "Lean 4": "leanpub",
  "Liquid / JS": "shopify",
  "Lua": "lua",
  "MSL (Metal)": "apple",
  "Metabase / Power BI": "metabase",
  "MicroPython": "micropython",
  "Mojo": "modal",
  "Move": "sui",
  "Next.js": "nextdotjs",
  "Next.js + Payload": "nextdotjs",
  "Next.js + Recharts": "nextdotjs",
  "Next.js + Stripe": "nextdotjs",
  "Next.js + Supabase (RLS)": "nextdotjs",
  "Next.js + Supabase + Stripe Connect": "nextdotjs",
  "Next.js + Supabase + shadcn/ui": "nextdotjs",
  "Next.js + Supabase Realtime": "nextdotjs",
  "Next.js + Vercel AI SDK": "nextdotjs",
  "Next.js PWA + IndexedDB": "nextdotjs",
  "Nim": "nim",
  "Nix": "nixos",
  "Node + Socket.IO": "nodedotjs",
  "OCaml": "ocaml",
  "Objective-C": "apple",
  "Odin": "odin",
  "OpenCL": "khronosgroup",
  "PHP": "php",
  "PL/pgSQL": "postgresql",
  "Perl": "perl",
  "Phoenix": "phoenixframework",
  "Phoenix Channels / LiveView": "phoenixframework",
  "Progress ABL (OpenEdge)": "progress",
  "Puppet DSL": "puppet",
  "PureScript": "purescript",
  "Python": "python",
  "Quarkus / Spring Boot": "quarkus",
  "R": "r",
  "Racket": "racket",
  "Rails + Hotwire": "rubyonrails",
  "Rails + Stripe Connect": "rubyonrails",
  "ReScript": "rescript",
  "React + Puppeteer (HTML to PDF)": "react",
  "React Native (JS/TS)": "react",
  "React Native + Expo": "react",
  "React Native + WatermelonDB": "react",
  "ReportLab / WeasyPrint": "python",
  "Ruby": "ruby",
  "Rust": "rust",
  "Rust (Solana / ink!)": "solana",
  "SPARK": "ada",
  "SQL": "postgresql",
  "Scala": "scala",
  "Scratch": "scratch",
  "Shiny": "rstudioide",
  "Shopify": "shopify",
  "Solidity": "solidity",
  "Spring Boot": "springboot",
  "Standard ML": "ocaml",
  "Starlark": "bazel",
  "Streamlit": "streamlit",
  "Streamlit / Plotly Dash": "streamlit",
  "Structured Text (IEC 61131-3)": "siemens",
  "Sui / Aptos": "sui",
  "Swift": "swift",
  "SwiftUI": "swift",
  "TOML": "toml",
  "Three.js / React Three Fiber": "threedotjs",
  "TypeScript": "typescript",
  "Unity": "unity",
  "Unreal Engine": "unrealengine",
  "UnrealScript": "unrealengine",
  "V (Vlang)": "v",
  "Vala": "vala",
  "Verse": "epicgames",
  "Visual Basic .NET": "dotnet",
  "Vyper": "ethereum",
  "WGSL": "webgpu",
  "WebAssembly (WAT)": "webassembly",
  "Wolfram Language": "wolfram",
  "WordPress": "wordpress",
  "WordPress (headless)": "wordpress",
  "XQuery / XSLT": "xml",
  "YAML": "yaml",
  "Zig": "zig",
  "Zsh": "zsh",
  "n8n / Make / Zapier": "n8n",
  "net/http / Gin": "go",
  "sed": "gnu"
};
